esphome:
  name: dreo-htf024s
  friendly_name: "Dreo HTF024S"
  platformio_options:
    #board_build.bkcrypt_coeffs: "123456782FAA55AA3AEE63DD4FEEAA00" does not really matter
    board_build.bkcrypt_coeffs: "00000000000000000000000000000000"
    board_build.bkota.key: "0123456789ABCDEF0123456789ABCDEF"
    board_build.bkota.iv: "0123456789ABCDEF"
    board_flash.calibration: "0x1E0000+0x1000"
    board_flash.download: "0x132000+0xAE000"

external_components:
  - source: github://davidc/dreo-protocol

bk72xx:
  board: generic-bk7231n-qfn32-tuya
  framework:
    version: latest
    # loglevel: debug # Turn this off if you don't need it

# Logging
logger:

# Home Assistant API
api:
  encryption:
    key: !secret dreo_htf024s_api_key

# OTA upgrades
ota:
  - platform: esphome
    password: !secret dreo_htf024s_ota_password

# WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Fallback hotspot (captive portal)
  ap:
    ssid: "Dreo-HTF024S"
    password: "12345678"

captive_portal:

# Enable UART
uart:
  tx_pin: TX1
  rx_pin: RX1
  baud_rate: 115200
  # debug:

# Enable Dreo MCU protocol via UART
dreo:

sensor:
  - id: current_temperature
    name: "Current Temperature"
    platform: dreo
    sensor_datapoint: 11
    device_class: temperature
    unit_of_measurement: °F

switch:
  - id: power
    name: "Power"
    platform: dreo
    switch_datapoint: 1
    disabled_by_default: true # Disabled by default because it's also available via the fan entity
  - id: display_always_on
    name: "Display Always On"
    platform: dreo
    switch_datapoint: 2
  - id: beeper
    name: "Beeper"
    platform: dreo
    switch_datapoint: 5
    inverted: true
  - id: oscillation
    name: "Oscillation"
    platform: dreo
    switch_datapoint: 8
    disabled_by_default: true # Disabled by default because it's also available via the fan entity

select:
  - id: mode
    name: "Mode"
    platform: dreo
    enum_datapoint: 3
    options:
      1: Normal
      2: Natural
      3: Sleep
      4: Auto

number:
  - id: fan_speed
    name: "Fan Speed"
    platform: dreo
    number_datapoint: 4
    min_value: 1
    max_value: 9
    step: 1
    disabled_by_default: true # Disabled by default because it's also available via the fan entity

  - id: auto_off_timer
    name: "Auto Off Timer"
    platform: dreo
    number_datapoint: 7
    min_value: 0
    max_value: 719 # 11 hours 59 minutes is the max in the app
    step: 1

fan:
  - id: fan_entity
    name: "Fan"
    platform: dreo
    restore_mode: RESTORE_DEFAULT_OFF
    switch_datapoint: 1
    speed_datapoint: 4
    speed_count: 9
    oscillation_datapoint: 8


# Differences from HTF018S per https://github.com/davidc/dreo-protocol/issues/1:
# Changed auto-off timer dp to 7
# dp 5 beeper is reversed